#!/bin/bash

apt-get update

# get kernel version
KVER=`uname -r`

# install headers
apt-get install -y linux-headers-$KVER

# install and build with wireguard-dkms
apt-get install -y --no-install-recommends wireguard-dkms bc
