#!/bin/bash

apt update

# get kernel version
KVER=`uname -r`

# install headers
apt install -y linux-headers-$KVER

# install and build with wireguard-dkms
apt install -y --no-install-recommends wireguard-dkms
