#!/usr/bin/env bash

apt update

UNAME=$(uname -r)
GENMODS=$(apt list linux-headers-generic 2>/dev/null |grep -v Listing)
INSTALL=""

if [ -n "${GENMODS}" ]; then
	# If `linux-headers-generic` is available, we are Ubuntu
	INSTALL="linux-headers-${UNAME} linux-headers-generic wireguard-dkms"
else
	# If `linux-headers-generic` is not available, we are Debian
	INSTALL="linux-headers-${UNAME} linux-headers-amd64 wireguard-dkms"
fi

if [ -n "${INSTALL}" ]; then
	# Use the defined packages
	apt install -y ${INSTALL}
else
	# No package architecture, default to cloud
	apt install -y linux-headers-cloud-amd64 linux-headers-amd64 wireguard-dkms
fi
